### ISSUE TITLE
info

### ISSUE THREAD

**Issue by LucaFerrantedev** [MrKiwi24/PirateARG#1]
no se muy bien como se usa esto de github. pero tiro la data q tengo: 
dodi repacks es bueno tambien dodi-repacks.site es el link si no me equivoco)
**cs.rin.ru** foro sobre juegos de steam, tiran archivos por ahi. lo uso.
**1337x.to** algunos dicen que no pero a mi siempre me funco sin drama
**torrentgalaxy.to** para peliculas/series y los subtitulos los podes conseguir en **subdivx.com**

**Comment by MrKiwi24** [comment]
En los FAQs hablo de las fuentes que voy a usar. Todas tienen esas páginas.
